"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { AlertCircle } from "lucide-react";
import { BarcodeScanner } from "@/components/barcode-scanner";

// Interface for the data inside the QR code
interface ScanData {
  id: string;
  time?: string;
  address?: string;
  location?: string;
  coordinates?: {
    latitude: number;
    longitude: number;
  };
}

interface BarcodeCheckInDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  checkInType: "in" | "out";
  setCheckInType: (type: "in" | "out") => void;
  // UPDATED: onScan now accepts the full data object
  onScan: (data: ScanData) => void;
}

export function BarcodeCheckInDialog({
  open,
  onOpenChange,
  checkInType,
  setCheckInType,
  onScan,
}: BarcodeCheckInDialogProps) {
  const [validationError, setValidationError] = useState<string | null>(null);

  const handleScan = (barcode: string) => {
    setValidationError(null);

    // Default fallback if it's just a plain barcode string
    let scannedData: ScanData = { id: barcode };

    try {
      // 1. Try to parse as JSON (Format generated by Mobile App)
      const data = JSON.parse(barcode);

      if (data && data.id) {
        scannedData = data; // Use the parsed object

        // Check for Freelancer restriction
        const uId = (data.id as string).toUpperCase();
        if (uId.startsWith("FRL") || uId.startsWith("FL-")) {
          setValidationError(
            "Barcode check-in is restricted to Employees and Trainees only. Freelancers must use manual check-in.",
          );
          return;
        }

        // Check for timestamp expiration (5 minutes)
        if (data.time) {
          const generatedTime = new Date(data.time);
          const now = new Date();
          const diffInMs = now.getTime() - generatedTime.getTime();
          const diffInMinutes = diffInMs / (1000 * 60);

          if (diffInMinutes > 5) {
            setValidationError(
              "This QR pass has expired (older than 5 minutes). Please ask the employee to refresh their pass.",
            );
            return;
          }
        }
      }
    } catch (error) {
      // If JSON parse fails, treat as raw string ID (e.g. printed card)
      const uBarcode = barcode.toUpperCase();
      if (uBarcode.startsWith("FRL") || uBarcode.startsWith("FL-")) {
        setValidationError(
          "Barcode check-in is restricted to Employees and Trainees only. Freelancers must use manual check-in.",
        );
        return;
      }
    }

    // FIX: Pass the full data object, not just the ID string
    onScan(scannedData);
    onOpenChange(false);
  };

  const handleOpenChange = (isOpen: boolean) => {
    if (!isOpen) setValidationError(null);
    onOpenChange(isOpen);
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>Barcode Check-In/Out</DialogTitle>
          <DialogDescription>
            Scan <strong>employee or trainee</strong> QR code to process
            attendance.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {validationError && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertTitle>Check-In Failed</AlertTitle>
              <AlertDescription>{validationError}</AlertDescription>
            </Alert>
          )}

          <div className="space-y-2">
            <Label>Check-In Type</Label>
            <Select
              value={checkInType}
              onValueChange={(value: "in" | "out") => setCheckInType(value)}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="in">Check In</SelectItem>
                <SelectItem value="out">Check Out</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <BarcodeScanner onScan={handleScan} />
        </div>
      </DialogContent>
    </Dialog>
  );
}

