import { Project, Task, TeamMember, Invoice } from "@/types/project";

export const teamMembers: TeamMember[] = [
  { id: "1", name: "Alice Johnson", role: "Project Manager", avatar: "AJ" },
  { id: "2", name: "Bob Smith", role: "Developer", avatar: "BS" },
  { id: "3", name: "Carol Davis", role: "Designer", avatar: "CD" },
  { id: "4", name: "David Wilson", role: "QA Engineer", avatar: "DW" },
  { id: "5", name: "Emma Brown", role: "Product Manager", avatar: "EB" },
  { id: "6", name: "Frank Miller", role: "Tech Lead", avatar: "FM" },
];

export const projects: Project[] = [
  {
    id: "1",
    name: "E-commerce Platform",
    description: "Modern e-commerce platform with advanced features",
    manager: "Alice Johnson",
    client: "TechCorp Solutions",
    status: "active",
    priority: "high",
    startDate: "2025-08-15",
    endDate: "2025-08-30",
    progress: 75,
    teamSize: 8,
    budget: 250000,
    invoiceTotal: 187500,
  },
  {
    id: "2",
    name: "Mobile Banking App",
    description:
      "Secure mobile banking application with biometric authentication",
    manager: "Emma Brown",
    client: "FirstBank International",
    status: "active",
    priority: "high",
    startDate: "2025-09-01",
    endDate: "2025-09-15",
    progress: 45,
    teamSize: 12,
    budget: 480000,
    invoiceTotal: 216000,
  },
  {
    id: "3",
    name: "Analytics Dashboard",
    description: "Business intelligence dashboard for data visualization",
    manager: "Frank Miller",
    client: "DataInsights Ltd",
    status: "completed",
    priority: "medium",
    startDate: "2025-06-01",
    endDate: "2025-06-29",
    progress: 100,
    teamSize: 5,
    budget: 120000,
    invoiceTotal: 120000,
  },
  {
    id: "4",
    name: "Learning Management System",
    description: "Online learning platform for educational institutions",
    manager: "Alice Johnson",
    client: "EduTech Academy",
    status: "on-hold",
    priority: "low",
    startDate: "2025-08-01",
    endDate: "2025-08-02",
    progress: 20,
    teamSize: 6,
    budget: 180000,
    invoiceTotal: 36000,
  },
  {
    id: "5",
    name: "Healthcare Portal",
    description: "Patient management system for healthcare providers",
    manager: "Emma Brown",
    client: "MediCare Systems",
    status: "active",
    priority: "medium",
    startDate: "2025-08-06",
    endDate: "2025-08-10",
    progress: 60,
    teamSize: 10,
    budget: 320000,
    invoiceTotal: 192000,
  },
];

export const tasks: Task[] = [
  {
    id: "1",
    projectId: "1",
    title: "Design user authentication flow",
    description: "Create wireframes and mockups for login/signup process",
    status: "completed",
    priority: "high",
    assignee: "Carol Davis",
    dueDate: "2025-02-15",
    createdAt: "2025-01-20",
  },
  {
    id: "2",
    projectId: "1",
    title: "Implement product catalog",
    description: "Build responsive product listing with filters and search",
    status: "in-progress",
    priority: "high",
    assignee: "Bob Smith",
    dueDate: "2025-08-01",
    createdAt: "2025-08-10",
  },
  {
    id: "3",
    projectId: "1",
    title: "Set up payment gateway",
    description: "Integrate Stripe payment processing",
    status: "todo",
    priority: "medium",
    assignee: "David Wilson",
    dueDate: "2025-08-15",
    createdAt: "2025-08-21",
  },
  {
    id: "4",
    projectId: "2",
    title: "Security audit",
    description: "Conduct comprehensive security testing",
    status: "in-progress",
    priority: "high",
    assignee: "Frank Miller",
    dueDate: "2025-02-28",
    createdAt: "2025-02-10",
  },
  {
    id: "5",
    projectId: "2",
    title: "Biometric authentication",
    description: "Implement fingerprint and face recognition",
    status: "todo",
    priority: "high",
    assignee: "Bob Smith",
    dueDate: "2025-03-20",
    createdAt: "2025-02-15",
  },
  {
    id: "6",
    projectId: "5",
    title: "Patient data migration",
    description: "Migrate existing patient records to new system",
    status: "in-progress",
    priority: "medium",
    assignee: "David Wilson",
    dueDate: "2025-03-10",
    createdAt: "2025-02-05",
  },
];

export const invoices: Invoice[] = [
  {
    id: "INV-001",
    projectId: "1",
    invoiceNumber: "INV-2025-001",
    amount: 62500,
    issuedDate: "2025-01-30",
    dueDate: "2025-02-29",
    status: "paid",
    description: "Initial development phase - Q1 2025",
  },
  {
    id: "INV-002",
    projectId: "1",
    invoiceNumber: "INV-2025-002",
    amount: 62500,
    issuedDate: "2025-02-28",
    dueDate: "2025-03-30",
    status: "paid",
    description: "Development progress - Q1 2025",
  },
  {
    id: "INV-003",
    projectId: "1",
    invoiceNumber: "INV-2025-003",
    amount: 62500,
    issuedDate: "2025-03-31",
    dueDate: "2025-04-30",
    status: "pending",
    description: "Q2 Development milestone",
  },
  {
    id: "INV-004",
    projectId: "2",
    invoiceNumber: "INV-2025-004",
    amount: 96000,
    issuedDate: "2025-02-15",
    dueDate: "2025-03-15",
    status: "paid",
    description: "Security implementation phase",
  },
  {
    id: "INV-005",
    projectId: "2",
    invoiceNumber: "INV-2025-005",
    amount: 120000,
    issuedDate: "2025-03-15",
    dueDate: "2025-04-15",
    status: "overdue",
    description: "Authentication module development",
  },
  {
    id: "INV-006",
    projectId: "3",
    invoiceNumber: "INV-2025-006",
    amount: 120000,
    issuedDate: "2025-01-31",
    dueDate: "2025-02-28",
    status: "paid",
    description: "Final payment - Project completion",
  },
  {
    id: "INV-007",
    projectId: "5",
    invoiceNumber: "INV-2025-007",
    amount: 96000,
    issuedDate: "2025-02-20",
    dueDate: "2025-03-20",
    status: "paid",
    description: "Healthcare portal - Phase 1",
  },
  {
    id: "INV-008",
    projectId: "5",
    invoiceNumber: "INV-2025-008",
    amount: 96000,
    issuedDate: "2025-03-20",
    dueDate: "2025-04-20",
    status: "pending",
    description: "Healthcare portal - Phase 2",
  },
];
export const mockTeam = [
  {
    id: 1,
    name: "Sarah Johnson",
    role: "Project Manager",
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: 2,
    name: "Mike Chen",
    role: "Frontend Developer",
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: 3,
    name: "Emily Davis",
    role: "UI/UX Designer",
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: 4,
    name: "Alex Wilson",
    role: "Backend Developer",
    avatar: "/placeholder.svg?height=32&width=32",
  },
];
