import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  // Glass/Mirrors
  {
    id: "1",
    name: "Tempered Glass Panel 6mm",
    category: "Glass/Mirrors",
    size: "1200x800mm",
    price: 85.0,
    description:
      "High-quality tempered safety glass, suitable for shower screens and partitions",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Bathroom Mirror 10mm",
    category: "Glass/Mirrors",
    size: "900x600mm",
    price: 120.0,
    description: "Polished edge bathroom mirror with safety backing",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    name: "Custom Cut Mirror",
    category: "Glass/Mirrors",
    size: "1500x1000mm",
    price: 180.0,
    description: "Custom cut mirror for wardrobe doors or feature walls",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },

  // Garage Doors - Normal
  {
    id: "4",
    name: "Standard Sectional Door",
    category: "Garage Doors - Normal",
    size: "2400x2100mm",
    price: 850.0,
    panels: 4,
    description: "Insulated sectional garage door with standard hardware",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "5",
    name: "Premium Sectional Door",
    category: "Garage Doors - Normal",
    size: "2400x2400mm",
    price: 1200.0,
    panels: 5,
    description: "Premium insulated sectional door with decorative hardware",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },

  // Garage Doors - Frameless
  {
    id: "6",
    name: "Frameless Glass Door Single",
    category: "Garage Doors - Frameless",
    size: "2400x2100mm",
    price: 2200.0,
    panels: 1,
    description: "Modern frameless glass garage door with electric opener",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "7",
    name: "Frameless Glass Door Double",
    category: "Garage Doors - Frameless",
    size: "4800x2100mm",
    price: 3800.0,
    panels: 2,
    description: "Double frameless glass garage door system",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },

  // Single Garage Doors - Normal
  {
    id: "8",
    name: "Single Panel Door",
    category: "Single Garage Doors - Normal",
    size: "2100x2100mm",
    price: 650.0,
    panels: 1,
    description: "Single panel tilt door for compact garages",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "9",
    name: "Insulated Single Door",
    category: "Single Garage Doors - Normal",
    size: "2200x2200mm",
    price: 780.0,
    panels: 1,
    description: "Insulated single panel door with weather seals",
    createdAt: new Date("2024-02-03"),
    updatedAt: new Date("2024-02-03"),
  },

  // Single Garage Doors - Frameless
  {
    id: "10",
    name: "Compact Frameless Door",
    category: "Single Garage Doors - Frameless",
    size: "2100x2100mm",
    price: 1800.0,
    panels: 1,
    description: "Compact frameless glass door for single car garages",
    createdAt: new Date("2024-02-08"),
    updatedAt: new Date("2024-02-08"),
  },

  // Kitchen Doors
  {
    id: "11",
    name: "Shaker Style Cabinet Door",
    category: "Kitchen Doors",
    size: "600x400mm",
    price: 45.0,
    description: "Classic shaker style cabinet door in white finish",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "12",
    name: "Modern Flat Panel Door",
    category: "Kitchen Doors",
    size: "800x600mm",
    price: 65.0,
    description: "Sleek modern flat panel door in charcoal gray",
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-01-28"),
  },
  {
    id: "13",
    name: "Glass Insert Cabinet Door",
    category: "Kitchen Doors",
    size: "600x800mm",
    price: 85.0,
    description: "Cabinet door with frosted glass insert for display",
    createdAt: new Date("2024-02-12"),
    updatedAt: new Date("2024-02-12"),
  },

  // Other
  {
    id: "14",
    name: "Custom Shower Screen",
    category: "Other",
    size: "1200x2000mm",
    price: 320.0,
    description: "Custom fitted shower screen with chrome fittings",
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
  },
  {
    id: "15",
    name: "Office Partition Panel",
    category: "Other",
    size: "1000x2400mm",
    price: 280.0,
    description: "Glass office partition panel with aluminum frame",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "16",
    name: "Balcony Balustrade Glass",
    category: "Other",
    size: "1500x1200mm",
    price: 450.0,
    description: "Structural glass panel for balcony balustrade",
    createdAt: new Date("2024-02-18"),
    updatedAt: new Date("2024-02-18"),
  },
];
